### ISSUE TITLE
Misleading naming

### ISSUE THREAD

**Issue by phosei** [seibert-media/automatix#26]
Example:
```
name: foobar
systems:
  darling: some-bundlewrap-node-name

pipeline:
  - python: |
      print(darling_node)
```
Issues with this syntax:

* `darling_node` creates the impression that we’re talking about a normal variable name here. We do not. It is a “composed” name, referring to the “system” `darling`.
* Users might (accidentally) clobber this name.
* If, for some reason, you don’t have `bundlewrap: true` in your `.automatix.cfg.yaml`, you just get a `name is not defined` error by Python. Yes, this is a user error, but it illustrates that it might not be the best idea to use “magic” variable names.

Ideas:

* Use a function, e.g. `get_node(darling)` or even `get_bw_node(darling)`.
* Introduce new objects like `NODES`, so you can write `NODES.darling`. @fkusei might want to elaborate on this.
* Both approaches can be implemented in a backwards-compatible way, so we don’t require rewriting all existing YAML files.
